version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: date-fns
    versions:
    - 2.20.2
    - 2.21.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.23.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.3
  - dependency-name: ioredis
    versions:
    - 4.24.2
    - 4.24.3
  - dependency-name: swr
    versions:
    - 0.4.1
    - 0.5.3
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: next
    versions:
    - 10.0.7
    - 10.0.8
  - dependency-name: "@types/ioredis"
    versions:
    - 4.19.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: chrome-aws-lambda
    versions:
    - 7.0.0
  - dependency-name: puppeteer-core
    versions:
    - 7.0.1
